### ISSUE TITLE
POST /waypoints crashes program

### ISSUE THREAD

**Issue by 21chanas3** [ubcuas/GCOM-Lite#8] opened 2023-02-04 18:51 UTC
Sending the JSON body below to attempt to create a new Waypoint crashes the program and send the error message `sql: no rows in result set`

## Reproduction Steps
POST this
```json
[
  {
    "id": -1,
    "name": "Alpha",
    "longitude": 0,
    "latitude": 0,
    "altitude": null
  }
]
```
to `/waypoints`

**Comment by kenndu** [comment] 2023-03-04 21:42
Was caused by allowing nullable float type for altitude, fixed now

**Closed as completed by kenndu** 2023-03-04 21:42 UTC
